import os
import sys

import numpy as np
from astropy.io import fits
from astropy.table import Table


def get_evt_data(obsid, post_fix="_barycorr_PHASE"):
    """
    Get the event data for a given observation ID.
    """
    event_filename = f"/Users/jacobpayne/Projects/Astronomyprojects/nicer_obs/{obsid}/xti/event_cl/ni{obsid}_0mpu7_cl{post_fix}.evt"
    hdu_list = fits.open(event_filename, memmap=True)
    evt_data = Table(hdu_list[1].data)

    # # Print information about the EVT file
    # hdu_list.info()
    # print(hdu_list[1].columns)
    # evt_data #print the Table
    return evt_data


# read xamin table
def read_xamin_table(filepath):
    """
    Reads the xamin table from a given file path.

    Args:
        filepath (str): Path to the xamin table file.

    Returns:
        Table: An Astropy Table containing the xamin data.
    """
    try:
        xamin_table = Table.read(filepath, format="ascii")
        # return a list of the column "obsid"
        if "obsid" in xamin_table.colnames:
            xamin_table["obsid"] = xamin_table["obsid"].astype(str)
        else:
            print(
                "Warning: 'obsid' column not found in xamin table.",
                file=sys.stderr,
            )
            return None
        return xamin_table["obsid"].tolist()
    except Exception as e:
        print(f"Error reading xamin table: {e}", file=sys.stderr)
        sys.exit(1)


def write_barycorr_sh(obsids, target_pulsar):
    """
    Generates a shell script for processing NICER pulsar data.

    Args:
        obsid (str): The NICER observation ID.
        target_pulsar (str): The name of the target pulsar (e.g., "B0531+21").
    """
    from pulsar_dictionary import pulsar_coords

    if target_pulsar not in pulsar_coords:
        print(
            f"Error: Pulsar '{target_pulsar}' not found in the predefined list.",
            file=sys.stderr,
        )
        sys.exit(1)
    pulsar_info = pulsar_coords[target_pulsar]
    right_ascension = pulsar_info["ra"]
    declination = pulsar_info["dec"]
    f_0 = pulsar_info["frequency"]
    f_dot = pulsar_info["f_dot"]
    f_epoch = pulsar_info["frequency_epoch"]

    obsroot = "/Users/jacobpayne/Projects/Astronomyprojects/nicer_obs/"

    for obsid in obsids:
        # get the observation time from the evt file
        observation_nicertime = get_evt_data(obsid, post_fix="")[0][0]

        # project f to the epoch of the observation
        # print(f"Frequency correction for {obsid}: {f_0} Hz at epoch {f_epoch}")
        # f = f_0 + f_dot * (observation_nicertime - f_epoch)
        print(
            f"Using frequency: {f_0} Hz at epoch {f_epoch} and observation start time {observation_nicertime}"
        )

        # make a new shell script file
        script_content = f"""#!/bin/bash
        # This script was generated by a Python script.
        # It automates the processing of NICER pulsar data,
        # including barycenter correction and phase calculation.

        # --- Script Execution ---

        echo "Starting NICER data processing for observation ID: {obsid}, pulsar: {target_pulsar}"

        # Step 1: Change to the observation root directory
        echo "Changing directory to {obsroot}"
        cd "{obsroot}" || {{ echo "Error: Could not change to obsroot. Exiting."; exit 1; }}

        # Step 2: Run nicerl2
        echo "Running nicerl2 for obsid {obsid}..."
        nicerl2 {obsid} clobber=YES || {{ echo "Error: nicerl2 failed. Exiting."; exit 1; }}

        # Step 3: Change to the event_cl directory
        echo "Changing directory to ./{obsid}/xti/event_cl/"
        cd ./{obsid}/xti/event_cl/ || {{ echo "Error: Could not change to ./{obsid}/xti/event_cl/. Exiting."; exit 1; }}

        # Step 4: Perform barycenter correction
        if [ -f "ni{obsid}_0mpu7_cl_barycorr.evt" ]; then
            echo "Removing existing outfile: ni{obsid}_0mpu7_cl_barycorr.evt..."
            rm ni{obsid}_0mpu7_cl_barycorr.evt
        fi

        echo "\n Writing barycenter correction along the LoS to pulsar {target_pulsar} (RA: {right_ascension}, Dec: {declination})"
        barycorr infile=ni{obsid}_0mpu7_cl.evt \\
                outfile=ni{obsid}_0mpu7_cl_barycorr.evt \\
                orbitfiles=../../auxil/ni{obsid}.orb \\
                ra={right_ascension} \\
                dec={declination} \\
                barytime=yes || {{ echo "Error: barycorr failed. Exiting."; exit 1; }}

        # Step 5: Create BARY_REF_TIME based on the barycenter and reference ephemeris time
        echo "\n Calculating BARY_REF_TIME"
        ftcalc infile='ni{obsid}_0mpu7_cl_barycorr.evt[events]' \\
            outfile=ni{obsid}_0mpu7_cl_barycorr.evt \\
            column=BARY_REF_TIME \\
            expression='(BARYTIME-{f_epoch})' \\
            clobber=yes || {{ echo "Error: ftcalc for BARY_REF_TIME failed. Exiting."; exit 1; }}

        # Step 6: Calculate PHASE
        if [ -f "ni{obsid}_0mpu7_cl_barycorr_PHASE.evt" ]; then
            echo "Removing existing outfile: ni{obsid}_0mpu7_cl_barycorr_PHASE.evt..."
            rm "ni{obsid}_0mpu7_cl_barycorr_PHASE.evt"
        fi

        echo "Calculating PHASE using frequency: {f_0} and f_dot: {f_dot}"
        ftcalc infile='ni{obsid}_0mpu7_cl_barycorr.evt[events]' \\
            outfile=ni{obsid}_0mpu7_cl_barycorr_PHASE.evt \\
            column=PHASE \\
            expression='(({f_0}*(BARY_REF_TIME)+({f_dot}*(BARY_REF_TIME**2)/2))%1)' \\
            clobber=yes || {{ echo "Error: ftcalc for PHASE failed. Exiting."; exit 1; }}

        echo "Script finished successfully for {target_pulsar} (ObsID: {obsid})."
        """
        script_filename = f"{obsroot}process_nicer_{obsid}.sh"
        with open(script_filename, "w") as script_file:
            script_file.write(script_content)
        print(f"Shell script written to {script_filename}")
        os.chmod(script_filename, 0o755)  # Make the script executable

    return
