import datetime
import os
import sys

from astropy.io import fits
from astropy.table import Table


def get_evt_data(obsid, post_fix="_barycorr_PHASE"):
    """
    Get the event data for a given observation ID.
    """
    event_filename = f"/Users/jacobpayne/Projects/Astronomyprojects/nicer_obs/{obsid}/xti/event_cl/ni{obsid}_0mpu7_cl{post_fix}.evt"
    hdu_list = fits.open(event_filename, memmap=True)
    evt_data = Table(hdu_list[1].data)

    # # Print information about the EVT file
    # hdu_list.info()
    # print(hdu_list[1].columns)
    # evt_data #print the Table
    return evt_data


# read xamin table
def read_xamin_table(filepath):
    """
    Reads the xamin table from a given file path.

    Args:
        filepath (str): Path to the xamin table file.

    Returns:
        Table: An Astropy Table containing the xamin data.
    """
    try:
        xamin_table = Table.read(filepath, format="ascii")
        # return a list of the column "obsid"
        if "obsid" in xamin_table.colnames:
            xamin_table["obsid"] = xamin_table["obsid"].astype(str)
        else:
            print(
                "Warning: 'obsid' column not found in xamin table.",
                file=sys.stderr,
            )
            return None
        return xamin_table["obsid"].tolist()
    except Exception as e:
        print(f"Error reading xamin table: {e}", file=sys.stderr)
        sys.exit(1)


def write_unpack_nicer_sh(obsids, target_pulsar):
    ### unzip and nicerl2

    obsroot = "/Users/jacobpayne/Projects/Astronomyprojects/nicer_obs/"

    for obsid in obsids:
        # prep text for gunzip
        gunzip_text = (
            f"gunzip -f {obsid}/auxil/ni{obsid}.orb.gz\n"
            f"gunzip -f {obsid}/auxil/ni{obsid}.mkf.gz\n"
            f"gunzip -f {obsid}/auxil/ni{obsid}.att.gz\n"
            f"gunzip -f {obsid}/xti/event_cl/ni{obsid}_0mpu7_cl.evt.gz\n"
            f"gunzip -f {obsid}/xti/event_cl/ni{obsid}_0mpu7_ufa.evt.gz\n"
        )
        for mpu in range(7):
            gunzip_text += f"gunzip -f {obsid}/xti/event_uf/ni{obsid}_0mpu{mpu}_uf.evt.gz\n"
            gunzip_text += (
                f"gunzip -f {obsid}/xti/hk/ni{obsid}_0mpu{mpu}.hk.gz\n"
            )

        # make a new shell script file
        script_content = f"""#!/bin/bash
# This script was generated by a Python script.
# Generated on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# It automates the unpacking and pre-processing of NICER pulsar data.

# --- Script Execution ---

echo "Starting NICER data unpacking and preprocessing for observation ID: {obsid}, pulsar: {target_pulsar}"

# Step 1: Change to the observation root directory
echo "Changing directory to {obsroot}"
cd "{obsroot}" || {{ echo "Error: Could not change to obsroot. Exiting."; exit 1; }}

# Step 1.1: Unzip the gzipped evt files
echo "Unzipping files for obsid {obsid}..."
{gunzip_text}

# Step 1.2:  Remove the gzipped files
echo "Removing gzipped files for obsid {obsid}..."
rm {obsid}/auxil/*.gz
rm {obsid}/xti/event_cl/*.gz
rm {obsid}/xti/event_uf/*.gz
rm {obsid}/xti/hk/*.gz

# Step 2: Run nicerl2
echo "Running nicerl2 for obsid {obsid}..."
nicerl2 {obsid} clobber=YES || {{ echo "Error: nicerl2 failed. Exiting."; exit 1; }}

echo "Script unpacked (ObsID: {obsid})  successfully for {target_pulsar}."
"""
        script_filename = f"{obsroot}unpack_nicer_{obsid}.sh"
        # check if the script already exists, if so, remove it
        if os.path.exists(script_filename):
            print(f"Script {script_filename} already exists. Removing it.")
            os.remove(script_filename)
        # then make a new shell script file
        with open(script_filename, "w") as script_file:
            script_file.write(script_content)
        print(f"Shell script written to {script_filename}")
        os.chmod(script_filename, 0o755)  # Make the script executable

    return


def write_barycorr_sh(obsids, target_pulsar, verbose=False, use_ra_dec=True):
    ### barycorr, BARY_REF_TIME, and phase calc

    # from pulsar_dictionary import pulsar_coords
    from pulsar_dictionary import pulsar_dict

    if target_pulsar not in pulsar_dict:
        print(
            f"Error: Pulsar '{target_pulsar}' not found in the predefined list.",
            file=sys.stderr,
        )
        sys.exit(1)
    pulsar_info = pulsar_dict[target_pulsar]
    right_ascension = pulsar_info["ra"]
    declination = pulsar_info["dec"]
    frequency = pulsar_info["frequency"]
    f_dot = pulsar_info["f_dot"]
    f_epoch = pulsar_info["frequency_epoch"]

    obsroot = "/Users/jacobpayne/Projects/Astronomyprojects/nicer_obs/"

    for obsid in obsids:
        # prep text for gunzip
        gunzip_text = (
            f"gunzip -f {obsid}/auxil/ni{obsid}.orb.gz\n"
            f"gunzip -f {obsid}/auxil/ni{obsid}.mkf.gz\n"
            f"gunzip -f {obsid}/auxil/ni{obsid}.att.gz\n"
            f"gunzip -f {obsid}/xti/event_cl/ni{obsid}_0mpu7_cl.evt.gz\n"
            f"gunzip -f {obsid}/xti/event_cl/ni{obsid}_0mpu7_ufa.evt.gz\n"
        )
        for mpu in range(7):
            gunzip_text += f"gunzip -f {obsid}/xti/event_uf/ni{obsid}_0mpu{mpu}_uf.evt.gz\n"
            gunzip_text += (
                f"gunzip -f {obsid}/xti/hk/ni{obsid}_0mpu{mpu}.hk.gz\n"
            )

        # make a new shell script file
        script_content = f"""#!/bin/bash
# This script was generated by a Python script.
# Generated on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# It automates the processing of NICER pulsar data,
# including barycenter correction and phase calculation.

# --- Script Execution ---

echo "Starting NICER data processing for observation ID: {obsid}, pulsar: {target_pulsar}"

# Step 1: Change to the observation root directory
echo "Changing directory to {obsroot}"
cd "{obsroot}" || {{ echo "Error: Could not change to obsroot. Exiting."; exit 1; }}

# Step 2: Change to the event_cl directory
echo "Changing directory to ./{obsid}/xti/event_cl/"
cd ./{obsid}/xti/event_cl/ || {{ echo "Error: Could not change to ./{obsid}/xti/event_cl/. Exiting."; exit 1; }}"""

        if use_ra_dec:
            script_content += f"""
# Step 3: Perform barycenter correction
if [ -f "ni{obsid}_0mpu7_cl_barycorr.evt" ]; then
    echo "Removing existing outfile: ni{obsid}_0mpu7_cl_barycorr.evt..."
    rm ni{obsid}_0mpu7_cl_barycorr.evt
fi

echo "\n Writing barycenter correction along the LoS to pulsar {target_pulsar} (RA: {right_ascension}, Dec: {declination})"
barycorr infile=ni{obsid}_0mpu7_cl.evt \\
        outfile=ni{obsid}_0mpu7_cl_barycorr.evt \\
        orbitfiles=../../auxil/ni{obsid}.orb \\
        ra={right_ascension} \\
        dec={declination} \\
        refframe=ICRS ephem=JPLEPH.430 \\
        barytime=yes || {{ echo "Error: barycorr failed. Exiting."; exit 1; }}

# Step 4: Create BARY_REF_TIME based on the barycenter and reference ephemeris time
echo "\n Calculating BARY_REF_TIME"
ftcalc infile='ni{obsid}_0mpu7_cl_barycorr.evt[events]' \\
    outfile=ni{obsid}_0mpu7_cl_barycorr.evt \\
    column=BARY_REF_TIME \\
    expression='(BARYTIME-{f_epoch})' \\
    clobber=yes || {{ echo "Error: ftcalc for BARY_REF_TIME failed. Exiting."; exit 1; }}
"""
        else:
            script_content += f"""
# Step 3: Perform barycenter correction without RA and Dec
if [ -f "ni{obsid}_0mpu7_cl_barycorr.evt" ]; then
    echo "Removing existing outfile: ni{obsid}_0mpu7_cl_barycorr.evt..."
    rm ni{obsid}_0mpu7_cl_barycorr.evt
fi

echo "\n Writing barycenter correction along the LoS to pulsar {target_pulsar} using pointing information without RA and Dec"
barycorr infile=ni{obsid}_0mpu7_cl.evt \\
        outfile=ni{obsid}_0mpu7_cl_barycorr.evt \\
        orbitfiles=../../auxil/ni{obsid}.orb \\
        refframe=ICRS ephem=JPLEPH.430 \\
        barytime=yes || {{ echo "Error: barycorr failed. Exiting."; exit 1; }}

# Step 4: Create BARY_REF_TIME based on the barycenter and reference ephemeris time
echo "\n Calculating BARY_REF_TIME"
ftcalc infile='ni{obsid}_0mpu7_cl_barycorr.evt[events]' \\
    outfile=ni{obsid}_0mpu7_cl_barycorr.evt \\
    column=BARY_REF_TIME \\
    expression='(BARYTIME-{f_epoch})' \\
    clobber=yes || {{ echo "Error: ftcalc for BARY_REF_TIME failed. Exiting."; exit 1; }}
"""
        if verbose:
            script_content += f"""
    # Step 5: Calculate PHASE with VERBOSE=TRUE print intermediate values in PHASE calculation
    if [ -f "ni{obsid}_0mpu7_cl_barycorr_PHASE.evt" ]; then
        echo "Removing existing outfile: ni{obsid}_0mpu7_cl_barycorr_PHASE.evt..."
        rm "ni{obsid}_0mpu7_cl_barycorr_PHASE.evt"
    fi

    echo "Calculating PHASE using frequency: {frequency} and f_dot: {f_dot}"
    ftcalc infile='ni{obsid}_0mpu7_cl_barycorr.evt[events]' \\
        outfile=ni{obsid}_0mpu7_cl_barycorr_PHASE.evt \\
        column=FT \\
        expression='({frequency}*(BARY_REF_TIME))' \\
        clobber=yes || {{ echo "Error: ftcalc for PHASE failed. Exiting."; exit 1; }}

        
    ftcalc infile='ni{obsid}_0mpu7_cl_barycorr_PHASE.evt[events]' \\
        outfile=ni{obsid}_0mpu7_cl_barycorr_PHASE.evt \\
        column=TSQUARED \\
        expression='(BARY_REF_TIME**2)' \\
        clobber=yes || {{ echo "Error: ftcalc for PHASE failed. Exiting."; exit 1; }}

    ftcalc infile='ni{obsid}_0mpu7_cl_barycorr_PHASE.evt[events]' \\
        outfile=ni{obsid}_0mpu7_cl_barycorr_PHASE.evt \\
        column=FDOTTSQUAREDOVERTWO \\
        expression='({f_dot}*(TSQUARED)/2)' \\
        clobber=yes || {{ echo "Error: ftcalc for PHASE failed. Exiting."; exit 1; }}

    ftcalc infile='ni{obsid}_0mpu7_cl_barycorr_PHASE.evt[events]' \\
        outfile=ni{obsid}_0mpu7_cl_barycorr_PHASE.evt \\
        column=FTPLUSFDOTTSQUAREDOVERTWO \\
        expression='(FT+FDOTTSQUAREDOVERTWO)' \\
        clobber=yes || {{ echo "Error: ftcalc for PHASE failed. Exiting."; exit 1; }}

    ftcalc infile='ni{obsid}_0mpu7_cl_barycorr_PHASE.evt[events]' \\
        outfile=ni{obsid}_0mpu7_cl_barycorr_PHASE.evt \\
        column=PHASE \\
        expression='(((((FTPLUSFDOTTSQUAREDOVERTWO)/10000)%1)*10000)%1)' \\
        clobber=yes || {{ echo "Error: ftcalc for PHASE failed. Exiting."; exit 1; }}

    echo "Script finished (ObsID: {obsid}) successfully for {target_pulsar}."
    """
        else:
            script_content += f"""
    # Step 5: Calculate PHASE
    if [ -f "ni{obsid}_0mpu7_cl_barycorr_PHASE.evt" ]; then
        echo "Removing existing outfile: ni{obsid}_0mpu7_cl_barycorr_PHASE.evt..."
        rm "ni{obsid}_0mpu7_cl_barycorr_PHASE.evt"
    fi

    echo "Calculating PHASE using frequency: {frequency} and f_dot: {f_dot}"
    ftcalc infile='ni{obsid}_0mpu7_cl_barycorr.evt[events]' \\
        outfile=ni{obsid}_0mpu7_cl_barycorr_PHASE.evt \\
        column=PHASE \\
        expression='((((({frequency}*(BARY_REF_TIME)+({f_dot}*(BARY_REF_TIME**2)/2))/10000)%1)*10000)%1)' \\
        clobber=yes || {{ echo "Error: ftcalc for PHASE failed. Exiting."; exit 1; }}

    echo "Script finished (ObsID: {obsid}) successfully for {target_pulsar}."
    """
        script_filename = f"{obsroot}barycorr_phase_nicer_{obsid}.sh"
        # check if the script already exists, if so, remove it
        if os.path.exists(script_filename):
            print(f"Script {script_filename} already exists. Removing it.")
            os.remove(script_filename)
        # then make a new shell script file
        with open(script_filename, "w") as script_file:
            script_file.write(script_content)
        print(f"Shell script written to {script_filename}")
        os.chmod(script_filename, 0o755)  # Make the script executable

    return


def bulk_process(obsids, target_pulsar):
    ### Create a script to call multiple unpack and barycorr scripts

    prep_script = ""
    for obsid in obsids:
        prep_script += f'./unpack_nicer_{obsid}.sh || {{ echo "Error processing {obsid}. Exiting."; exit 1; }}\n'
        prep_script += f'./barycorr_phase_nicer_{obsid}.sh || {{ echo "Error processing {obsid}. Exiting."; exit 1; }}\n'

    script_content = f"""#!/bin/bash
# This script was generated by a Python script.
# Generated on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# It automates the processing of multiple NICER pulsar data.
# --- Script Execution ---
 echo "Starting bulk NICER data processing for pulsar: {target_pulsar}"
{prep_script}
echo "Bulk processing script finished successfully for pulsar: {target_pulsar}. "
"""

    script_filename = f"/Users/jacobpayne/Projects/Astronomyprojects/nicer_obs/process_nicer_bulk_{target_pulsar}.sh"
    with open(script_filename, "w") as script_file:
        script_file.write(script_content)
    print(f"Bulk processing shell script written to {script_filename}")
    os.chmod(script_filename, 0o755)  # Make the script executable

    return


def bulk_redo_phase_process(obsids, target_pulsar):
    ### Create a script to call multiple barycorr scripts, without filehandling nor calling nicerl2

    prep_script = ""
    for obsid in obsids:
        prep_script += f'./barycorr_phase_nicer_{obsid}.sh || {{ echo "Error processing {obsid}. Exiting."; exit 1; }}\n'

    script_content = f"""#!/bin/bash
# This script was generated by a Python script.
# Generated on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# It automates the processing of multiple NICER pulsar data.
# --- Script Execution ---
 echo "Starting bulk NICER data processing for pulsar: {target_pulsar}"
{prep_script}
echo "Bulk processing script finished successfully for pulsar: {target_pulsar}. "
"""

    script_filename = f"/Users/jacobpayne/Projects/Astronomyprojects/nicer_obs/process_nicer_bulk_{target_pulsar}.sh"
    with open(script_filename, "w") as script_file:
        script_file.write(script_content)
    print(f"Bulk processing shell script written to {script_filename}")
    os.chmod(script_filename, 0o755)  # Make the script executable

    return
